version: '3.1'
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-api:
    container_name: auth-api
    build:
      context: ./login-api

  login:
    container_name: login
    build:
      context: ./login

  api-gateway:
    container_name: api-gateway
    restart: always
    image: nginx:latest
    volumes:
      - "./api-gateway/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"

volumes:
  db:
    driver: local
