version: '3.1'
networks:
  service-net:
    name: vpc
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      service-net:
        ipv4_address: 172.22.0.3

  auth-api:
    container_name: auth-api
    build:
      context: ./login-api
    networks:
      service-net:
        ipv4_address: 172.22.0.4

  login:
    container_name: login
    build:
      context: ./login
    networks:
      service-net:
        ipv4_address: 172.22.0.5

  api-gateway:
    container_name: api-gateway
    restart: always
    image: nginx:latest
    volumes:
      - "./api-gateway/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
    networks:
      service-net:
        ipv4_address: 172.22.0.6

volumes:
  db:
    driver: local
